CREATE TABLE GENERO(
    descricao VARCHAR(50) PRIMARY KEY
);

CREATE TABLE ATOR(
    nomeReal VARCHAR(100) PRIMARY KEY,
    sexo CHAR(1)
);

CREATE TABLE FILME(
    id INTEGER PRIMARY KEY,
    nome VARCHAR(100),
    anoEstreia INTEGER,
    descricaoGenero VARCHAR(50) NOT NULL,
    FOREIGN KEY (descricaoGenero) REFERENCES GENERO(descricao)
);

CREATE TABLE DVD(
    id INTEGER PRIMARY KEY,
    idFilme INTEGER NOT NULL,
    FOREIGN KEY (idFilme) REFERENCES FILME(id)
);

CREATE TABLE ELENCO(
    idFilme INTEGER,
    nomeAtor VARCHAR(100),
    PRIMARY KEY (idFilme, nomeAtor),
    FOREIGN KEY (idFilme) REFERENCES FILME(id),
    FOREIGN KEY (nomeAtor) REFERENCES ATOR(nomeReal)
);
